title: Jekyll Nerd Portfolio
name: Jam Risser
email: jam@jamrizzi.com
description: Jekyll portfolio for nerds
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
github_fork_banner: https://github.com/jamrizzi/jekyll-nerd-portfolio
skills:
  - icon: amazonwebservices-plain-wordmark
    href: https://aws.amazon.com
    title: Amazon Web Services
isso_url: https://example.com
comments: false
markdown: kramdown
theme: jekyll-nerd-portfolio
plugins:
  - jekyll-feed
  - jekyll-read-time
