title: Jekyll Nerd Portfolio
name: Jam Risser
email: jam@jamrizzi.com
description: Jekyll portfolio for nerds
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
github_fork_banner: https://github.com/jamrizzi/jekyll-nerd-portfolio
skills:
  amazonwebservices: https://aws.amazon.com
  react: https://github.com/facebook/react
  ruby: https://www.ruby-lang.org
  nodejs: https://nodejs.org
  python: https://python.com
  linux: https://kernel.org
markdown: kramdown
theme: jekyll-nerd-portfolio
plugins:
  - jekyll-feed
  - jekyll-read-time
